### PR TITLE
Refactoring the flightplan scripts to return GeoJson from every modules 

### PR DESCRIPTION
**Pull request by nrjadkry**
Refactoring modules with precisely specified inputs and outputs that can be displayed and inspected offline (in QGIS or similar) or in the UX (using frontend geo libraries)

## Module 1 - calculate_parameters
**Input - Parameters:** Dict/namespace from user-supplied arguments

- altitude_from_ground_level
- GSD
- Forward Overlap
- Side Overlap
- Image Interval

**Output** - JSON
Example Output: 
```
   {
    'forward_photo_height': 84.0,
    'side_photo_width': 149.0,
    'forward_spacing': 20.95,
    'side_spacing': 44.6,
    'ground_speed': 10.47,
    'altitude_above_ground_level': 118
    }
```

## Module 2 - Waypoints
This module takes a geojson polygon along with the parameters calculated from the `calculate_parameters` module and generates a list of waypoint coordinates along with few more parameters such as heading direction, etc.

Input
 - Geojson Polygon 
 - Parameters calculated from calculate_parameters.py

Output
 - Waypoints file in a geojson format

## Module 3 - Add Elevation
This module accepts the waypoints geojson and add the elevation to the waypoints.
It also requires the DEM file to add the elevation to the geojson file.

This module is done in this PR: https://github.com/hotosm/drone-flightplan/pull/4

## Module 4 - Create Placemarks
This module also accepts the waypoints geojson either with the elevation or without the elevation and returns the geojson file ready to be used in the placemarks in the wpml file to be made in drone filghtplan.

## Module5 - Create_wpml
This module accepts the placemark geojson obtained from create_placemark module and converts it into the wpml file for the drone flightplan.

### CODE REVIEW

**Comment by ivangayton** [comment]
Hi Niraj,

Looking at this quickly, a few comments:

## Pull request to main or dev
It looks like the pull request is pointed to `main` instead of `dev`. Is that intentional? Is your online API using the code from `main`? If so, wouldn't it be better to point this (and other) pull requests to `dev` and then merge to main after testing?

## What to include in output
It seems like you're only including the calculated fields, and will continue to rely upon the original parameters for everything else. So going forward, you'll need to refer to two different objects, the original namespace from argparse for some parameters, and the JSON generated by this module. 

Why not create a JSON here that has everything needed to create the waypoints, and nothing more? I think that would be something like:
```
AOI: polygon
DEM: GeoTIFF
agl: float # m 
ground_speed: float # m/s
photo_interval: float # sec (float, not an int, because we might want to take a picture every 2.5 sec)
forward_spacing: float # m
side_spacing: float # m
wayline_heading: int # degrees between 0° and 360° (we don't have a way to do that yet but later we probably will)
gimbal_angles # list of tuples, one for each individual angle, normally one for 2D and three for 3D
  [
    angle_1(pitch: int, roll: int, yaw: int)
    angle_2(pitch: int, roll: int, yaw: int)
    angle_2(pitch: int, roll: int, yaw: int)
  ]
all_waypoints: bool # if false, waylines. If terrain following and waylines, one waypoint after threshold elevation change
elevation_change_threshold: float # m, basically how much elevation change we tolerate before creating another waypoint
```

I may have forgotten some parameters here, but the basic idea is: this module returns a single object and you _never have to look at the original parameter namespace again_. You can pass this object into the rest of the process and never look back.

You can safely discard some things; once you calculate the forward spacing, side spacing, and airspeed, you don't need to retain overlap information. That's done. The waypoint generation module then doesn't need to know about FOV angles or anything related to overlap, they just get fed spacing. All of the calculations get done here, and the waypoint creation module can be kept simple and straightforward.

Similarly, you don't need to retain `generate_3D`, because that's only used to determine the number of different gimbal angles used and the spacing (with three angles we take 3x as many photos, so the spacing is 3x smaller). The waypoint generation module doesn't need to know if it's creating 2D or 3D flight plans, it just needs to know what spacing and gimbal angles to use.

I'm not certain that I would discard the fields like `generate_3D` and overlap. Maybe it makes sense to keep them even if they aren't used, but I do think it's actually quite important to ensure that the waypoint generation module doesn't require or ask for anything more than what it needs to know; any further retained information should be explicitly just for information for a person auditing the data flow. 

 ## Readability and editability
Maybe the most important thing about the output of this module is that it should be really clear and easy for someone (or some program) to understand what's going on, and possibly edit it. 

Example, say I'm mapping on a hillside, and I want the lateral photos to be pointing toward the hillside to capture images under canopy. Instead of asking the developer to create a new option for me, I can edit this JSON file and feed it into the waypoint generation model. It gives me, the user, a lot more options if I can inspect, understand, and (at need) modify this file, and then feed it (and it alone) to the next step in the process.

**Comment by nrjadkry** [comment]
Hi @ivangayton 

## About Pull request

Online API is from the main branch. It uses a python package, not the main branch. So, unless it is fully tested, we dont really need to relese a new version and then the API wont crash. But, yes you are right, creating a PR to dev branch and then merging dev into main branch might be the better approach.

## Output format
I did not include the other parameters since they do not have any impact on the output of this program. For example, this module (create_waypoints) do not requires an AOI, DEM because they do not have any relation with the output of this module. They come into action in the waypoints generation steps.

**Comment by ivangayton** [comment]
Hi @nrjadkry this is looking really good.

Among other things, I think it'll make it easier for others to contribute; @spwoodcock has already identified an Outreachy intern who's keen to contribute on this repo. 

I notice it's still marked as Work-In-Progress, but I don't see any reason not to already merge it with `dev` so that me and others can already base off of this setup. I've already gone over it and don't see any issues, shall we just point it at `dev` and merge it?

**Comment by spwoodcock** [comment]
For the modules we haven't been using a `dev` branch and I'm not sure we necessarily need one.

The Drone-TM repo as a software tool has a flow dev --> staging --> prod, but this package as a **module** is managed by it's release version.

We then pin the versions of packages used downstream in Drone-TM.

It's simpler to just do feature branch --> `main` --> release (a version increment) 👍

**Comment by spwoodcock** [comment]
All of the above to say this can be merged into `main` without issues!

(we can make a new release when everything is working)

**Comment by spwoodcock** [comment]
This change is ideal for debugging 👍

In the future we can look into wrapping this functionality in a higher level function that handles this all for you.

The CLI could simply have a `--debug` flag where the intermediate outputs are dumped at every step before moving to the next

**Comment by nrjadkry** [comment]
Same thought here @spwoodcock 
Since this is a python package, this can be merged into `main` branch directly instead of having a `dev` branch seperate.

I think I am done for all the modules now, we can merge it.

**Comment by ivangayton** [comment]
Hmm, I guess I should get rid of the `dev` branch if its not needed to prevent merges from breaking stuff anyone is using!

**Pull request merged**
